config/routes.rb
Rails.application.routes.draw do

  resources :diagrams
  resources :ontologies
  get 'ontologies/:id/query', to: 'ontologies#sparql_query', as: 'sparql'

  resources :lanes
  resources :business_processes
  get '/bpmn/modeler' => 'bpmn#modeler'
  get '/bpmn/viewer' => 'bpmn#viewer'
  get '/bpmn/parser' => 'bpmn#parser'
  get '/bpmn/create' => 'bpmn#create'
#  post 'sparql' => 'ontologies#sparql_query'

  resources :sequence_flows
  resources :tasks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "home#index"
  
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sequence_flow.rb
class SequenceFlow < ApplicationRecord
  belongs_to :target, class_name: 'Task', foreign_key: 'target_id', inverse_of: :previous_sequence_flows, optional: true
  belongs_to :source, class_name: 'Task', foreign_key: 'source_id', inverse_of: :next_sequence_flows, optional: true

  rails_admin do
    edit do
      field :target
      field :source
      field :xml_id
    end
    list do
      field :target
      field :source
      field :xml_id
    end
    show do
      field :target
      field :source
      field :xml_id
    end
  end

end

app/controllers/sequence_flows_controller.rb
class SequenceFlowsController < ApplicationController
  before_action :set_sequence_flow, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /sequence_flows
  # GET /sequence_flows.json
  def index
    @sequence_flows = SequenceFlow.all
  end

  # GET /sequence_flows/1
  # GET /sequence_flows/1.json
  def show
  end

  # GET /sequence_flows/new
  def new
    @sequence_flow = SequenceFlow.new
  end

  # GET /sequence_flows/1/edit
  def edit
  end

  # POST /sequence_flows
  # POST /sequence_flows.json
  def create
    @sequence_flow = SequenceFlow.new(sequence_flow_params)

    respond_to do |format|
      if @sequence_flow.save
        format.html { redirect_to @sequence_flow, notice: 'Sequence flow was successfully created.' }
        format.json { render :show, status: :created, location: @sequence_flow }
      else
        format.html { render :new }
        format.json { render json: @sequence_flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequence_flows/1
  # PATCH/PUT /sequence_flows/1.json
  def update
    respond_to do |format|
      if @sequence_flow.update(sequence_flow_params)
        format.html { redirect_to @sequence_flow, notice: 'Sequence flow was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence_flow }
      else
        format.html { render :edit }
        format.json { render json: @sequence_flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequence_flows/1
  # DELETE /sequence_flows/1.json
  def destroy
    @sequence_flow.destroy
    respond_to do |format|
      format.html { redirect_to sequence_flows_url, notice: 'Sequence flow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence_flow
      @sequence_flow = SequenceFlow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_flow_params
      params.require(:sequence_flow).permit(:target, :source)
    end
end

app/helpers/sequence_flows_helper.rb
module SequenceFlowsHelper
end

app/views/sequence_flows/_form.html.erb
<%= form_with(model: sequence_flow, local: true) do |form| %>
  <% if sequence_flow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sequence_flow.errors.count, "error") %> prohibited this sequence_flow from being saved:</h2>

      <ul>
      <% sequence_flow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :target %>
    <%= form.number_field :target, id: :sequence_flow_target %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.number_field :source, id: :sequence_flow_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sequence_flows/edit.html.erb
<h1>Editing Sequence Flow</h1>

<%= render 'form', sequence_flow: @sequence_flow %>

<%= link_to 'Show', @sequence_flow %> |
<%= link_to 'Back', sequence_flows_path %>

app/views/sequence_flows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sequence Flows</h1>

<table>
  <thead>
    <tr>
      <th>Target</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sequence_flows.each do |sequence_flow| %>
      <tr>
        <td><%= sequence_flow.target %></td>
        <td><%= sequence_flow.source %></td>
        <td><%= link_to 'Show', sequence_flow %></td>
        <td><%= link_to 'Edit', edit_sequence_flow_path(sequence_flow) %></td>
        <td><%= link_to 'Destroy', sequence_flow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sequence Flow', new_sequence_flow_path %>

app/views/sequence_flows/new.html.erb
<h1>New Sequence Flow</h1>

<%= render 'form', sequence_flow: @sequence_flow %>

<%= link_to 'Back', sequence_flows_path %>

app/views/sequence_flows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Target:</strong>
  <%= @sequence_flow.target %>
</p>

<p>
  <strong>Source:</strong>
  <%= @sequence_flow.source %>
</p>

<%= link_to 'Edit', edit_sequence_flow_path(@sequence_flow) %> |
<%= link_to 'Back', sequence_flows_path %>