config/routes.rb
Rails.application.routes.draw do

  resources :diagrams
  resources :ontologies
  get 'ontologies/:id/query', to: 'ontologies#sparql_query', as: 'sparql'

  resources :lanes
  resources :business_processes
  get '/bpmn/modeler' => 'bpmn#modeler'
  get '/bpmn/viewer' => 'bpmn#viewer'
  get '/bpmn/parser' => 'bpmn#parser'
  get '/bpmn/create' => 'bpmn#create'
#  post 'sparql' => 'ontologies#sparql_query'

  resources :sequence_flows
  resources :tasks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "home#index"
  
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/diagram.rb
class Diagram < ApplicationRecord
  has_many :business_processes, inverse_of: :diagram

  mount_uploader :file, DiagramUploader # Tells rails to use this uploader for this model.
  mount_uploader :image, DiagramUploader
  validates_presence_of :file
  before_save :get_name


  rails_admin do
    edit do
      include_all_fields
      field :name do
        read_only true
      end
    end

  end

  private
  def get_name
    self.name = self.file.path.split('/').last.split('.').first
  end
end

app/controllers/diagrams_controller.rb
class DiagramsController < ApplicationController
  before_action :set_diagram, only: [:show, :edit, :update, :destroy]

  # GET /diagrams
  # GET /diagrams.json
  def index
    @diagrams = Diagram.all
  end

  # GET /diagrams/1
  # GET /diagrams/1.json
  def show
  end

  # GET /diagrams/new
  def new
    @diagram = Diagram.new
  end

  # GET /diagrams/1/edit
  def edit
  end

  # POST /diagrams
  # POST /diagrams.json
  def create
    @diagram = Diagram.new(diagram_params)

    respond_to do |format|
      if @diagram.save
        format.html { redirect_to @diagram, notice: 'Diagram was successfully created.' }
        format.json { render :show, status: :created, location: @diagram }
      else
        format.html { render :new }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagrams/1
  # PATCH/PUT /diagrams/1.json
  def update
    respond_to do |format|
      if @diagram.update(diagram_params)
        format.html { redirect_to @diagram, notice: 'Diagram was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagram }
      else
        format.html { render :edit }
        format.json { render json: @diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagrams/1
  # DELETE /diagrams/1.json
  def destroy
    @diagram.destroy
    respond_to do |format|
      format.html { redirect_to diagrams_url, notice: 'Diagram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagram
      @diagram = Diagram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagram_params
      params.require(:diagram).permit(:name, :file, :image)
    end
end

app/helpers/diagrams_helper.rb
module DiagramsHelper
end

app/views/diagrams/_form.html.erb
<%= form_with(model: diagram, local: true) do |form| %>
  <% if diagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diagram.errors.count, "error") %> prohibited this diagram from being saved:</h2>

      <ul>
      <% diagram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :diagram_name %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.text_field :file, id: :diagram_file %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :diagram_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diagrams/edit.html.erb
<h1>Editing Diagram</h1>

<%= render 'form', diagram: @diagram %>

<%= link_to 'Show', @diagram %> |
<%= link_to 'Back', diagrams_path %>

app/views/diagrams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diagrams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diagrams.each do |diagram| %>
      <tr>
        <td><%= diagram.name %></td>
        <td><%= diagram.file %></td>
        <td><%= diagram.image %></td>
        <td><%= link_to 'Show', diagram %></td>
        <td><%= link_to 'Edit', edit_diagram_path(diagram) %></td>
        <td><%= link_to 'Destroy', diagram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagram', new_diagram_path %>

app/views/diagrams/new.html.erb
<h1>New Diagram</h1>

<%= render 'form', diagram: @diagram %>

<%= link_to 'Back', diagrams_path %>

app/views/diagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @diagram.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @diagram.file %>
</p>

<p>
  <strong>Image:</strong>
  <%= @diagram.image %>
</p>

<%= link_to 'Edit', edit_diagram_path(@diagram) %> |
<%= link_to 'Back', diagrams_path %>