config/routes.rb
Rails.application.routes.draw do

  resources :diagrams
  resources :ontologies
  get 'ontologies/:id/query', to: 'ontologies#sparql_query', as: 'sparql'

  resources :lanes
  resources :business_processes
  get '/bpmn/modeler' => 'bpmn#modeler'
  get '/bpmn/viewer' => 'bpmn#viewer'
  get '/bpmn/parser' => 'bpmn#parser'
  get '/bpmn/create' => 'bpmn#create'
#  post 'sparql' => 'ontologies#sparql_query'

  resources :sequence_flows
  resources :tasks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "home#index"
  
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ontology.rb
class Ontology < ApplicationRecord
  mount_uploader :path_name, OntologyUploader # Tells rails to use this uploader for this model.
  validates_presence_of :name
  validates_presence_of :prefix


end

app/controllers/ontologies_controller.rb
class OntologiesController < ApplicationController
  before_action :set_ontology, only: [:show, :edit, :update, :destroy, :sparql_query]
  before_action :authenticate_user!, only: [:show, :create, :edit, :update, :destroy]
  before_action :set_diagram, only: :sparql_query
  #load_and_authorize_resource
  skip_before_action :verify_authenticity_token

  include BpmnDirFileHandler
  include SparqlModule

  # GET /ontologies
  # GET /ontologies.json
  def index
    @ontologies = Ontology.all
  end

  # GET /ontologies/1
  # GET /ontologies/1.json
  def show
  end

  # GET /ontologies/new
  def new
    @ontology = Ontology.new
  end

  # GET /ontologies/1/edit
  def edit
  end

  # POST /ontologies
  # POST /ontologies.json
  def create
    @ontology = Ontology.new(ontology_params)

    respond_to do |format|
      if @ontology.save
        format.html { redirect_to @ontology, notice: 'Ontology was successfully created.' }
        format.json { render :show, status: :created, location: @ontology }
      else
        format.html { render :new }
        format.json { render json: @ontology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ontologies/1
  # PATCH/PUT /ontologies/1.json
  def update
    respond_to do |format|
      if @ontology.update(ontology_params)
        format.html { redirect_to @ontology, notice: 'Ontology was successfully updated.' }
        format.json { render :show, status: :ok, location: @ontology }
      else
        format.html { render :edit }
        format.json { render json: @ontology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ontologies/1
  # DELETE /ontologies/1.json
  def destroy
    @ontology.destroy
    respond_to do |format|
      format.html { redirect_to ontologies_url, notice: 'Ontology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 # POST ontologies/1
  def sparql_query

    # returns array with user_tasks
    response = parser_
    @results = user_task_sparql(@ontology.path_name.path, response)

    render 'result'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ontology
      @ontology = Ontology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ontology_params
      params.require(:ontology).permit(:path_name, :name, :prefix)
    end

    def set_diagram
      name = escape_(params[:bpmn_name])
      @diagram =Diagram.find_by_name(name)
    end
end

app/helpers/ontologies_helper.rb
module OntologiesHelper
end

app/views/ontologies/_form.html.erb
<%= form_with(model: ontology, local: true) do |form| %>
  <% if ontology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ontology.errors.count, "error") %> prohibited this ontology from being saved:</h2>

      <ul>
      <% ontology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :path_name %>
    <%= form.text_field :path_name, id: :ontology_path_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ontologies/edit.html.erb
<h1>Editing Ontology</h1>

<%= render 'form', ontology: @ontology %>

<%= link_to 'Show', @ontology %> |
<%= link_to 'Back', ontologies_path %>

app/views/ontologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ontologies</h1>

<table>
  <thead>
    <tr>
      <th>Path name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ontologies.each do |ontology| %>
      <tr>
        <td><%= ontology.path_name %></td>
        <td><%= link_to 'Show', ontology %></td>
        <td><%= link_to 'Edit', edit_ontology_path(ontology) %></td>
        <td><%= link_to 'Destroy', ontology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ontology', new_ontology_path %>

app/views/ontologies/new.html.erb
<h1>New Ontology</h1>

<%= render 'form', ontology: @ontology %>

<%= link_to 'Back', ontologies_path %>

app/views/ontologies/result.html.erb
<div class="row">

  <div class="jumbotron col-md-offset-1 col-md-10">
    <h1 class="display-3">SparQL result</h1>
      <table class="table table-bordered table-condensed table-hover">
        <thead class="thead-inverse">
        <tr>
          <th>Suggestion table</th>
        </tr>
        </thead>
        <tbody>
        <% @results.each do |result| %>
            <tr>
              <td><%=result %></td>
            </tr>
        <%end%>
        </tbody>
      </table>
    <hr class="my-4">
    <p class="lead">
      <a class="btn btn-primary btn-lg text-center" href="<%= bpmn_modeler_path %>" role="button">Apply changes?</a>
    </p>
  </div>

</div>

<div class="row">
  <div class="col-md-off-2 col-md-10 text-center">
    <%= image_tag(@diagram.image_url, class:"img-fluid img-thumbnail", alt:"Responsive image") %>
  </div>
</div>

app/views/ontologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path name:</strong>
  <%= @ontology.path_name %>

</p>

<%= link_to 'Edit', edit_ontology_path(@ontology) %> |
<%= link_to 'Back', ontologies_path %>

<p>
  <strong>Parse bpmn diagram to find the most suitable usertasks role for its task:</strong>
</p>

<%= form_tag(sparql_path, method: :get) do %>
    <div class="field">
      <%= hidden_field_tag(search: 'task_role') %>
      <%= hidden_field_tag(search: 'task_role') %>
      <%= hidden_field_tag(id: @ontology.id) %>
      <%= label_tag(:bpmn_name, 'BPMN process name:') %>
      <%= text_field_tag(:bpmn_name) %>

    </div>

    <div class="actions">
      <%= submit_tag('Find') %>
    </div>
<% end %>